### ISSUE TITLE
Should get submission id and call check_result before returning, in submit function

### ISSUE THREAD

**Issue by samyak-jain** [GDGVIT/competitive-cli#11]
https://github.com/GDGVIT/competitive-cli/blob/cf60bcd5b37384b61b775e7206b0ccd81fb9ad92/SessionAPI.py#L183

**Comment by apuayush** [comment]
return statement is submission id @samyak-jain.. and check_result we can give inside... we need to give a little time span for check_result() if added directly it displays "running..... " as status

**Comment by samyak-jain** [comment]
I didn't think of that. @Souldiv is there a similar problem for codeforces?
As for the solution for the problem - I believe we should keep sending requests to codechef until it gives us something other than running. @apuayush Is that possible?

**Comment by apuayush** [comment]
lemme check... or we can give little time gap.. till which it compiles the code. will notify if ur solution is possible.

**Comment by samyak-jain** [comment]
Amrut and I still need to work on this

**Comment by Souldiv** [comment]
Fixed for CodeForces in fixes #9
