### ISSUE TITLE
Need to check if login is successfull

### ISSUE THREAD

**Issue by samyak-jain** [GDGVIT/competitive-cli#16]
In the login function for the Uva and Codechef, there is no check for if the login was successful.

**Comment by samyak-jain** [comment]
@Souldiv please work on the Uva login function instead of me

**Comment by apuayush** [comment]
raise WrongCredentialsError in case of not logged in @samyak-jain  @Souldiv ..

**Comment by Souldiv** [comment]
CodeForces login returns a bool value.
On it @samyak-jain.

**Comment by samyak-jain** [comment]
@apuayush I don't see why using a custom exception class would be useful here. I think it would be better to simply return a bool which says whether the login was successful or not.

**Comment by apuayush** [comment]
So do that if successful return the response else return False

**Comment by samyak-jain** [comment]
Yeah, so we have to simply check it the login was successful by checking something like username in response page.

**Comment by apuayush** [comment]
Yeaa.. in case of codechef .. replace the raise command with return False or None
else return response

**Comment by apuayush** [comment]
removed custom exception https://github.com/GDGVIT/competitive-cli/commit/2bd9f248392fb51c4769520cb443f0116449ef91
