### ISSUE TITLE
User stats

### ISSUE THREAD

**Issue by samyak-jain** [GDGVIT/competitive-cli#9]
Create a function which will allow users to see user stats like ranking, problems solved etc.

**Comment by apuayush** [comment]
this issue is not yet resolved

**Comment by samyak-jain** [comment]
https://github.com/GDGVIT/competitive-cli/blob/336a6d75998852d0d387280f45fd0e0b0c391b67/SessionAPI.py#L277

@apuayush  What happens if no parameters are given?

**Comment by apuayush** [comment]
it will give userstats of all problems solved by the user it works like a filter

**Comment by samyak-jain** [comment]
https://github.com/GDGVIT/competitive-cli/blob/336a6d75998852d0d387280f45fd0e0b0c391b67/SessionAPI.py#L491

@Souldiv What is that?

**Comment by samyak-jain** [comment]
https://github.com/GDGVIT/competitive-cli/blob/6650e2d4caa51002677d211e0d8635f779c87f03/SessionAPI.py#L249

I believe the work of the above function that you have written is to display all submissions by the user. We should rename this function to ```display_sub()``` instead (like how @Souldiv has done in codeforces). The ```user_stats()``` function should give details about the user like ranking and other details codechef gives in your profile page.

**Comment by apuayush** [comment]
user_stats() name changed to display_sub() https://github.com/GDGVIT/competitive-cli/commit/d6fb4d1b2ce5142d746f34d43866d05f895a7846 ..

**Comment by samyak-jain** [comment]
Cool. Now only ```user_stats()``` function needs to be done.

**Comment by apuayush** [comment]
yeaa
on that
